BV3D documentation
BV3D::ClassicReferee
BV3D::ClassicReferee Class Reference
Implements the traditional volleyball rules.
#include <ClassicReferee.h>
Public Member Functions
ClassicReferee (VRS::SO< BV3D::Game > game)
~ClassicReferee (void)
void ballOnBlobb (BV3D::TEAM team)
void ballOnField (BV3D::TEAM team)
Detailed Description
Implements the traditional volleyball rules.
Traditional rules means, that only the team that served can get a point. If the serving team caused a fault the opponent team gets the serve, but no points. Teams can touch the ball only 3 times before causing a fault and the game goes until one team reaches a score of 15 or more with 2 or more points difference to the other team.
Definition at line 15 of file ClassicReferee.h.
Constructor & Destructor Documentation
BV3D::ClassicReferee::ClassicReferee (VRS::SO< BV3D::Game > game)
Sets up a Referee for classic volleyball rules, with a winning score of 15, a minimum difference between teams of 2 and a maximum of 3 contacts with the ball.
Definition at line 7 of file ClassicReferee.cpp.
References BV3D::Referee::setMaximumContacts(), BV3D::Referee::setMinimumDifference(), and BV3D::Referee::setWinningScore().
BV3D::ClassicReferee::~ClassicReferee (void) [inline]
Definition at line 20 of file ClassicReferee.h.
Member Function Documentation
void BV3D::ClassicReferee::ballOnBlobb (BV3D::TEAM team) [virtual]
Handles the case when the ball collides with a blobb from a team. Increases the teams contact-counter and checks whether a fault occured. If that is the case it increases the opponents score(if that team served the ball) and checks whether the game is now over. If not a new rally is started with the opponent team serving.
Implements BV3D::Referee.
Definition at line 20 of file ClassicReferee.cpp.
References BV3D::Referee::gameOver(), BV3D::Referee::getMaximumContacts(), BV3D::Referee::getOpponent(), BV3D::Referee::increaseContacts(), BV3D::Referee::increaseScore(), BV3D::Referee::isGameOver(), BV3D::Referee::mActive, BV3D::Referee::mGame, BV3D::Referee::mServingTeam, BV3D::Referee::newServe(), and BV3D::Referee::resetContacts().
void BV3D::ClassicReferee::ballOnField (BV3D::TEAM team) [virtual]
Handles the case when the ball touches the ground on a teams side. If the opponent team served the ball their score is increased. In that case a check is done whether the game is now over. The opponent team serves the new ball if the game is not over yet and all contact-counters are reset.
Implements BV3D::Referee.
Definition at line 60 of file ClassicReferee.cpp.
References BV3D::Referee::gameOver(), BV3D::Referee::getOpponent(), BV3D::Referee::increaseScore(), BV3D::Referee::isGameOver(), BV3D::Referee::mActive, BV3D::Referee::mGame, BV3D::Referee::mServingTeam, BV3D::Referee::newServe(), BV3D::Referee::resetContacts(), BV3D::TEAM1, and BV3D::TEAM2.
The documentation for this class was generated from the following files:
ClassicReferee.h
ClassicReferee.cpp