BV3D documentation
BV3D::Menu
BV3D::Menu Class Reference
#include <Menu.h>
Public Types
enum PLACE {
BEACH, HEAVEN, ARENA, CITY,
MAX_PLACES
}
enum RULES { CLASSIC, TIE_BREAK, MAX_RULES }
enum COLOR {
RED, GREEN, BLUE, YELLOW,
CORAL, CYAN, MAX_COLORS
}
enum CONTROLS {
KB_ARROWS, KB_WASDQ, MOUSE, AI,
MAX_CONTROLS
}
Public Member Functions
Menu (VRS::SO< Game > game)
virtual ~Menu ()
VRS::SO
< VRS::SceneThing > getScene ()
VRS::SO
< VRS::PickingCallback > getPickingCallback ()
void showMainMenu (bool paused)
CONTROLS getControls (BV3D::TEAM team)
VRS::Color getColor (BV3D::TEAM team)
RULES getRules ()
PLACE getPlace ()
Protected Member Functions
void select (VRS::IntersectionInfo *info)
void addText (const char *label, const char *command=0)
void showMenu (MENUSCREEN screen)
Static Protected Member Functions
static const char ** places ()
static const char ** rules ()
static const char ** fullscreen ()
static const VRS::Color * colors ()
static const char ** controls ()
Detailed Description
Definition at line 23 of file Menu.h.
Member Enumeration Documentation
enum BV3D::Menu::PLACE
Enumerator:
BEACH
HEAVEN
ARENA
CITY
MAX_PLACES
Definition at line 26 of file Menu.h.
enum BV3D::Menu::RULES
Enumerator:
CLASSIC
TIE_BREAK
MAX_RULES
Definition at line 27 of file Menu.h.
enum BV3D::Menu::COLOR
Enumerator:
RED
GREEN
BLUE
YELLOW
CORAL
CYAN
MAX_COLORS
Definition at line 28 of file Menu.h.
enum BV3D::Menu::CONTROLS
Enumerator:
KB_ARROWS
KB_WASDQ
MOUSE
AI
MAX_CONTROLS
Definition at line 29 of file Menu.h.
Constructor & Destructor Documentation
BV3D::Menu::Menu (VRS::SO< Game > game)
Menu.cpp
class BV3D::Menu implements the menu for bv3d
Definition at line 39 of file Menu.cpp.
References CITY, GREEN, KB_ARROWS, BV3D::MODELS_PATH, BV3D::ModelOptimizer::NO_MATERIAL_NO_TEXTURES, RED, select(), and TIE_BREAK.
virtual BV3D::Menu::~Menu () [inline, virtual]
Definition at line 37 of file Menu.h.
Member Function Documentation
VRS::SO<VRS::SceneThing> BV3D::Menu::getScene () [inline]
Definition at line 38 of file Menu.h.
VRS::SO<VRS::PickingCallback> BV3D::Menu::getPickingCallback () [inline]
Definition at line 39 of file Menu.h.
void BV3D::Menu::showMainMenu (bool paused)
Definition at line 206 of file Menu.cpp.
References showMenu().
CONTROLS BV3D::Menu::getControls (BV3D::TEAM team) [inline]
Definition at line 43 of file Menu.h.
VRS::Color BV3D::Menu::getColor (BV3D::TEAM team)
Definition at line 255 of file Menu.cpp.
References BV3D::BLOBB_ALPHA, and colors().
RULES BV3D::Menu::getRules () [inline]
Definition at line 45 of file Menu.h.
PLACE BV3D::Menu::getPlace () [inline]
Definition at line 46 of file Menu.h.
void BV3D::Menu::select (VRS::IntersectionInfo * info) [protected]
Definition at line 90 of file Menu.cpp.
References MAX_COLORS, MAX_CONTROLS, MAX_PLACES, MAX_RULES, and showMenu().
Referenced by Menu().
void BV3D::Menu::addText (const char * label, const char * command = 0) [protected]
Definition at line 212 of file Menu.cpp.
Referenced by showMenu().
void BV3D::Menu::showMenu (MENUSCREEN screen) [protected]
Definition at line 139 of file Menu.cpp.
References addText(), BV3D::BLOBB_ALPHA, colors(), controls(), fullscreen(), places(), and rules().
Referenced by select(), and showMainMenu().
static const char** BV3D::Menu::places () [inline, static, protected]
Definition at line 52 of file Menu.h.
Referenced by showMenu().
static const char** BV3D::Menu::rules () [inline, static, protected]
Definition at line 53 of file Menu.h.
Referenced by showMenu().
static const char** BV3D::Menu::fullscreen () [inline, static, protected]
Definition at line 54 of file Menu.h.
Referenced by showMenu().
static const VRS::Color* BV3D::Menu::colors () [inline, static, protected]
Definition at line 55 of file Menu.h.
Referenced by getColor(), and showMenu().
static const char** BV3D::Menu::controls () [inline, static, protected]
Definition at line 58 of file Menu.h.
Referenced by showMenu().
The documentation for this class was generated from the following files:
Menu.h
Menu.cpp