BV3D documentation
BV3D::Arena
BV3D::Arena Class Reference
The Arena class represents the box in which the Blobbs play Ball.
#include <Arena.h>
Public Member Functions
Arena (BV3D::Game *game)
~Arena ()
void setExtent (VRS::Vector extent)
VRS::Bounds getBounds ()
VRS::Bounds getTeamBounds (BV3D::TEAM team)
VRS::SO
< VRS::SceneThing > getScene ()
void updateWorld (float timestep)
NewtonWorld * getWorld ()
void createMaterials ()
void setupMaterials ()
int getBallMaterialID ()
int getBlobbMaterialID ()
int getWallMaterialID ()
int getFloorMaterialID ()
int getNetMaterialID ()
int getInvisibleBarrierID ()
int getAiTriggerID ()
Detailed Description
The Arena class represents the box in which the Blobbs play Ball.
It is responsible for:
setting up valid bounds for the Arena
passing valid bounds for Blobbs and the Ball
creating the 3D shape - a topless box with transparent walls
the Arena floor is centered at the origin the Net runs along the z-axis the individual fields run along the positive/negative x-axis the walls are transparent to see the play and still give some hint about Ball collision the box is assumed to be topless, still the walls have a certain height that should prevent the ball from bouncing out
Definition at line 42 of file Arena.h.
Constructor & Destructor Documentation
BV3D::Arena::Arena (BV3D::Game * game)
sets up an Arena with a predefined extent
Definition at line 25 of file Arena.cpp.
References BV3D::ARENA_EXTENT, createMaterials(), and setExtent().
BV3D::Arena::~Arena ()
Definition at line 52 of file Arena.cpp.
Member Function Documentation
void BV3D::Arena::setExtent (VRS::Vector extent)
resizes the Arena to the given extent the arena bottom is centered at the origin
Parameters:
extent is a Vector specifying the distance of each dimension of the Arena box
Definition at line 60 of file Arena.cpp.
References BV3D::ARENA_EXTENT, BV3D::MODELS_PATH, and BV3D::NET_HEIGHT.
Referenced by Arena().
VRS::Bounds BV3D::Arena::getBounds () [inline]
get the bounds of the whole arena
Definition at line 64 of file Arena.h.
VRS::Bounds BV3D::Arena::getTeamBounds (BV3D::TEAM team)
get the valid bounds for one of the blobbs
Definition at line 195 of file Arena.cpp.
References BV3D::TEAM2.
VRS::SO<VRS::SceneThing> BV3D::Arena::getScene () [inline]
get the local arena scene
Definition at line 74 of file Arena.h.
void BV3D::Arena::updateWorld (float timestep)
perform physics simulation
Parameters:
timestep specifies the amount of time in millisecs to advance during simulation
Definition at line 205 of file Arena.cpp.
NewtonWorld* BV3D::Arena::getWorld () [inline]
return pointer to the Physics world
Definition at line 86 of file Arena.h.
void BV3D::Arena::createMaterials ()
create Newton material IDs
Definition at line 209 of file Arena.cpp.
Referenced by Arena().
void BV3D::Arena::setupMaterials ()
Definition at line 220 of file Arena.cpp.
References BV3D::AI::AiCallback(), BV3D::CollisionData::arena, BV3D::CollisionData::ball, BV3D::CollisionData::game, BV3D::CollisionData::material1, BV3D::CollisionData::material2, BV3D::CollisionData::referee, and BV3D::CollisionData::world.
int BV3D::Arena::getBallMaterialID () [inline]
Definition at line 98 of file Arena.h.
int BV3D::Arena::getBlobbMaterialID () [inline]
Definition at line 99 of file Arena.h.
int BV3D::Arena::getWallMaterialID () [inline]
Definition at line 100 of file Arena.h.
int BV3D::Arena::getFloorMaterialID () [inline]
Definition at line 101 of file Arena.h.
int BV3D::Arena::getNetMaterialID () [inline]
Definition at line 102 of file Arena.h.
int BV3D::Arena::getInvisibleBarrierID () [inline]
Definition at line 103 of file Arena.h.
int BV3D::Arena::getAiTriggerID () [inline]
Definition at line 104 of file Arena.h.
The documentation for this class was generated from the following files:
Arena.h
Arena.cpp