BV3D documentation
BV3D::Blobb
BV3D::Blobb Class Reference
Represents the players in BlobbyVolley3D.
#include <Blobb.h>
Public Member Functions
Blobb (VRS::SO< BV3D::Arena > arena, BV3D::TEAM team, VRS::SO< VRS::LookAt > lookAt)
~Blobb ()
void setPosition (VRS::Vector position)
void setLookAt (VRS::SO< VRS::LookAt > lookAt)
void setControls (VRS::SO< BV3D::Controls > controls)
void setColor (VRS::Color color)
VRS::SO< BV3D::Controls > getControls ()
VRS::SO
< VRS::SceneThing > getScene ()
VRS::Color getColor ()
BV3D::TEAM getTeam ()
void updateShape (VRS::SO< VRS::Canvas > canvas)
void processInput (VRS::SO< VRS::InputEvent > ie)
void forceSingleAnimation ()
void maxJump ()
Static Public Member Functions
static void applyForceAndTorqueCallback (const NewtonBody *body)
Protected Member Functions
VRS::Vector getMovement ()
void update ()
Detailed Description
Represents the players in BlobbyVolley3D.
it is responsible for:
creating(loading) and managing: the 3D shape of the Blobb
forwarding InputEvents to its Controls
managing the Controls orientation and movement distance
updating the position based on input and physics.
Definition at line 33 of file Blobb.h.
Constructor & Destructor Documentation
BV3D::Blobb::Blobb (VRS::SO< BV3D::Arena > arena, BV3D::TEAM team, VRS::SO< VRS::LookAt > lookAt)
Parameters:
arena specifies the arena in which the blobb is simulated
Definition at line 20 of file Blobb.cpp.
References applyForceAndTorqueCallback(), BV3D::BLOBB_ALPHA, BV3D::BLOBB_SHAPE_DATA, BV3D::MODELS_PATH, BV3D::ModelOptimizer::NO_MATERIAL_NO_TEXTURES, setPosition(), and BV3D::SHADOW_HEIGHT.
BV3D::Blobb::~Blobb ()
Definition at line 119 of file Blobb.cpp.
Member Function Documentation
void BV3D::Blobb::setPosition (VRS::Vector position)
move blobb to specified position
Definition at line 132 of file Blobb.cpp.
References BV3D::BLOBB_SHAPE_DATA, BV3D::SHADOW_HEIGHT, and BV3D::SHADOW_MAX_HEIGHT.
Referenced by Blobb(), and update().
void BV3D::Blobb::setLookAt (VRS::SO< VRS::LookAt > lookAt) [inline]
Definition at line 38 of file Blobb.h.
void BV3D::Blobb::setControls (VRS::SO< BV3D::Controls > controls) [inline]
Definition at line 39 of file Blobb.h.
void BV3D::Blobb::setColor (VRS::Color color)
set the blobb's color
Definition at line 153 of file Blobb.cpp.
VRS::SO<BV3D::Controls> BV3D::Blobb::getControls () [inline]
Definition at line 41 of file Blobb.h.
VRS::SO<VRS::SceneThing> BV3D::Blobb::getScene () [inline]
Definition at line 42 of file Blobb.h.
VRS::Color BV3D::Blobb::getColor ()
returns the blobb's current color
Definition at line 160 of file Blobb.cpp.
BV3D::TEAM BV3D::Blobb::getTeam () [inline]
Definition at line 44 of file Blobb.h.
void BV3D::Blobb::updateShape (VRS::SO< VRS::Canvas > canvas)
Animates the blobb by switching the different blobb shapes on and off, depending on various circumstances, e.g. if the blobb is moving or jumping. At most one shape is active at any given moment.
Definition at line 169 of file Blobb.cpp.
void BV3D::Blobb::processInput (VRS::SO< VRS::InputEvent > ie)
processes user input for this blobb
Parameters:
ie is an input event that was explicitely forwarded from the input callback in BV3D::Game
Definition at line 209 of file Blobb.cpp.
void BV3D::Blobb::forceSingleAnimation ()
force the blobb to do one animation
Definition at line 332 of file Blobb.cpp.
Referenced by update().
void BV3D::Blobb::applyForceAndTorqueCallback (const NewtonBody * body) [static]
callback which notifies that a NewtonBody in the NewtonWorld has changed
Parameters:
body is the changed NewtonBody
Definition at line 316 of file Blobb.cpp.
Referenced by Blobb().
void BV3D::Blobb::maxJump ()
lets the blobb do a jump with maximum height
Definition at line 325 of file Blobb.cpp.
VRS::Vector BV3D::Blobb::getMovement () [protected]
evaluates the controls state and returns the movement vector for the current frame. this resets the controls state for the next frame.
Definition at line 218 of file Blobb.cpp.
References BV3D::BLOBB_JUMP_SPEED, and BV3D::BLOBB_MOVEMENT_STEP_DISTANCE.
Referenced by update().
void BV3D::Blobb::update () [protected]
updates physical and visual blobb (called every frame)
Definition at line 247 of file Blobb.cpp.
References BV3D::BLOBB_GRAVITY_MULTIPLIER, BV3D::BLOBB_HEIGHT, BV3D::BLOBB_MAX_JUMP_HEIGHT, BV3D::BLOBB_SHAPE_DATA, forceSingleAnimation(), getMovement(), BV3D::GRAVITY, setPosition(), BV3D::SHADOW_HEIGHT, and BV3D::SHADOW_MAX_HEIGHT.
The documentation for this class was generated from the following files:
Blobb.h
Blobb.cpp