BV3D documentation
BV3D::Referee
BV3D::Referee Class Reference
The Referee class is an abstract class for implementation of volleyball rules.
#include <Referee.h>
Public Member Functions
Referee (VRS::SO< BV3D::Game > game)
virtual ~Referee (void)
virtual void ballOnBlobb (BV3D::TEAM team)=0
virtual void ballOnField (BV3D::TEAM team)=0
VRS::SO< BV3D::Game > getGame ()
int getCurrentScore (BV3D::TEAM team)
void setCurrentScore (BV3D::TEAM team, int score)
int getCurrentContacts (BV3D::TEAM team)
void setCurrentContacts (BV3D::TEAM team, int contacts)
int getWinningScore ()
int getMaximumContacts ()
int getMinimumDifference ()
BV3D::BV3D_ERROR setWinningScore (int winningScore)
BV3D::BV3D_ERROR setMaximumContacts (int maxContacts)
BV3D::BV3D_ERROR setMinimumDifference (int minDifference)
void startNewGame ()
BV3D::TEAM getServingTeam ()
void setServingTeam (BV3D::TEAM team)
void setActive (bool b)
bool getActive ()
void setHUD (VRS::SO< BV3D::HUD > hud)
void gameOver (BV3D::TEAM winner)
bool isGameOver ()
Protected Member Functions
int increaseScore (BV3D::TEAM team)
int increaseContacts (BV3D::TEAM team)
void resetContacts (BV3D::TEAM team)
int getTeamIndex (BV3D::TEAM team)
BV3D::TEAM getOpponent (BV3D::TEAM team)
void newServe (BV3D::TEAM servingTeam)
Protected Attributes
VRS::SO< BV3D::Game > mGame
BV3D::TEAM mServingTeam
bool mActive
Detailed Description
The Referee class is an abstract class for implementation of volleyball rules.
It defines an interface for the usage of referee subclasses. It also already implements some getters/setters and elementary mehtods for score keeping and such. Referee-Classes are responsible for:
score keeping
identification of faults
taking actions if faults occur(starting a new rally(results in new serve), ending the game,...)
Definition at line 21 of file Referee.h.
Constructor & Destructor Documentation
BV3D::Referee::Referee (VRS::SO< BV3D::Game > game)
Definition at line 5 of file Referee.cpp.
References mActive, mGame, mServingTeam, and BV3D::TEAM1.
virtual BV3D::Referee::~Referee (void) [inline, virtual]
Definition at line 25 of file Referee.h.
Member Function Documentation
virtual void BV3D::Referee::ballOnBlobb (BV3D::TEAM team) [pure virtual]
Implemented in BV3D::ClassicReferee, and BV3D::TieBreakReferee.
virtual void BV3D::Referee::ballOnField (BV3D::TEAM team) [pure virtual]
Implemented in BV3D::ClassicReferee, and BV3D::TieBreakReferee.
VRS::SO<BV3D::Game> BV3D::Referee::getGame () [inline]
Definition at line 30 of file Referee.h.
References mGame.
int BV3D::Referee::getCurrentScore (BV3D::TEAM team)
Returns current score for individual teams
Definition at line 18 of file Referee.cpp.
References getTeamIndex().
void BV3D::Referee::setCurrentScore (BV3D::TEAM team, int score) [inline]
Definition at line 32 of file Referee.h.
int BV3D::Referee::getCurrentContacts (BV3D::TEAM team)
Returns current number of consecutive contacts with the ball for individual teams
Definition at line 26 of file Referee.cpp.
References getTeamIndex().
void BV3D::Referee::setCurrentContacts (BV3D::TEAM team, int contacts) [inline]
Definition at line 34 of file Referee.h.
int BV3D::Referee::getWinningScore () [inline]
Returns the score needed to win the game
Definition at line 38 of file Referee.h.
Referenced by isGameOver().
int BV3D::Referee::getMaximumContacts () [inline]
Returns the maximum number of consecutive contatcts one team might have without causing a fault
Definition at line 42 of file Referee.h.
Referenced by BV3D::TieBreakReferee::ballOnBlobb(), and BV3D::ClassicReferee::ballOnBlobb().
int BV3D::Referee::getMinimumDifference () [inline]
Returns the minumum difference between teams, needed to win the game
Definition at line 46 of file Referee.h.
Referenced by isGameOver().
BV3D::BV3D_ERROR BV3D::Referee::setWinningScore (int winningScore)
Sets the score needed to win the game Must not be less than 1
Definition at line 35 of file Referee.cpp.
References BV3D::INVALID_PARAMETER, and BV3D::NO_ERROR.
Referenced by BV3D::ClassicReferee::ClassicReferee(), and BV3D::TieBreakReferee::TieBreakReferee().
BV3D::BV3D_ERROR BV3D::Referee::setMaximumContacts (int maxContacts)
Sets the maximum number of consecutive contatcts one team might have without causing a fault Must not be less than 1
Definition at line 50 of file Referee.cpp.
References BV3D::INVALID_PARAMETER, and BV3D::NO_ERROR.
Referenced by BV3D::ClassicReferee::ClassicReferee(), and BV3D::TieBreakReferee::TieBreakReferee().
BV3D::BV3D_ERROR BV3D::Referee::setMinimumDifference (int minDifference)
Sets the minimum difference between teams needed to win the game Must not be less than 1
Definition at line 65 of file Referee.cpp.
References BV3D::INVALID_PARAMETER, and BV3D::NO_ERROR.
Referenced by BV3D::ClassicReferee::ClassicReferee(), and BV3D::TieBreakReferee::TieBreakReferee().
void BV3D::Referee::startNewGame ()
Resets all counters to 0 for a new game to start
Definition at line 79 of file Referee.cpp.
References mServingTeam, and BV3D::TEAM1.
BV3D::TEAM BV3D::Referee::getServingTeam () [inline]
Definition at line 51 of file Referee.h.
References mServingTeam.
void BV3D::Referee::setServingTeam (BV3D::TEAM team) [inline]
Definition at line 52 of file Referee.h.
References mServingTeam.
void BV3D::Referee::setActive (bool b) [inline]
Definition at line 53 of file Referee.h.
References mActive.
bool BV3D::Referee::getActive () [inline]
Definition at line 54 of file Referee.h.
References mActive.
void BV3D::Referee::setHUD (VRS::SO< BV3D::HUD > hud)
associates a HUD with the Referee and refreshes the HUD display
Parameters:
hud is the associated HUD
Definition at line 91 of file Referee.cpp.
References mServingTeam.
void BV3D::Referee::gameOver (BV3D::TEAM winner)
Triggers game over routine.
Definition at line 179 of file Referee.cpp.
Referenced by BV3D::TieBreakReferee::ballOnBlobb(), BV3D::ClassicReferee::ballOnBlobb(), BV3D::TieBreakReferee::ballOnField(), and BV3D::ClassicReferee::ballOnField().
bool BV3D::Referee::isGameOver ()
Returns whether one team has won the game
Definition at line 128 of file Referee.cpp.
References getMinimumDifference(), and getWinningScore().
Referenced by BV3D::TieBreakReferee::ballOnBlobb(), BV3D::ClassicReferee::ballOnBlobb(), BV3D::TieBreakReferee::ballOnField(), and BV3D::ClassicReferee::ballOnField().
int BV3D::Referee::increaseScore (BV3D::TEAM team) [protected]
Increases score of 'team' by 1
Definition at line 101 of file Referee.cpp.
References getTeamIndex(), BV3D::TEAM1, and BV3D::TEAM2.
Referenced by BV3D::TieBreakReferee::ballOnBlobb(), BV3D::ClassicReferee::ballOnBlobb(), BV3D::TieBreakReferee::ballOnField(), and BV3D::ClassicReferee::ballOnField().
int BV3D::Referee::increaseContacts (BV3D::TEAM team) [protected]
Increases contacts-counter of 'team' by 1
Definition at line 112 of file Referee.cpp.
References getTeamIndex().
Referenced by BV3D::TieBreakReferee::ballOnBlobb(), and BV3D::ClassicReferee::ballOnBlobb().
void BV3D::Referee::resetContacts (BV3D::TEAM team) [protected]
Resets contacts-counter of 'team' to 0
Definition at line 120 of file Referee.cpp.
References getTeamIndex().
Referenced by BV3D::TieBreakReferee::ballOnBlobb(), BV3D::ClassicReferee::ballOnBlobb(), BV3D::TieBreakReferee::ballOnField(), and BV3D::ClassicReferee::ballOnField().
int BV3D::Referee::getTeamIndex (BV3D::TEAM team) [protected]
Returns an index corresponding to a teams constant
Definition at line 147 of file Referee.cpp.
References BV3D::TEAM1, and BV3D::TEAM2.
Referenced by getCurrentContacts(), getCurrentScore(), increaseContacts(), increaseScore(), and resetContacts().
BV3D::TEAM BV3D::Referee::getOpponent (BV3D::TEAM team) [protected]
Returns the constant for opponent of 'team'
Definition at line 163 of file Referee.cpp.
References BV3D::TEAM1, and BV3D::TEAM2.
Referenced by BV3D::TieBreakReferee::ballOnBlobb(), BV3D::ClassicReferee::ballOnBlobb(), BV3D::TieBreakReferee::ballOnField(), and BV3D::ClassicReferee::ballOnField().
void BV3D::Referee::newServe (BV3D::TEAM servingTeam) [protected]
Starts a new rally with 'team' having the serve.
Definition at line 188 of file Referee.cpp.
References mGame, mServingTeam, BV3D::TEAM1, and BV3D::TEAM2.
Referenced by BV3D::TieBreakReferee::ballOnBlobb(), BV3D::ClassicReferee::ballOnBlobb(), BV3D::TieBreakReferee::ballOnField(), and BV3D::ClassicReferee::ballOnField().
Member Data Documentation
VRS::SO<BV3D::Game> BV3D::Referee::mGame [protected]
Definition at line 73 of file Referee.h.
Referenced by BV3D::TieBreakReferee::ballOnBlobb(), BV3D::ClassicReferee::ballOnBlobb(), BV3D::TieBreakReferee::ballOnField(), BV3D::ClassicReferee::ballOnField(), getGame(), newServe(), and Referee().
BV3D::TEAM BV3D::Referee::mServingTeam [protected]
Definition at line 74 of file Referee.h.
Referenced by BV3D::ClassicReferee::ballOnBlobb(), BV3D::ClassicReferee::ballOnField(), getServingTeam(), newServe(), Referee(), setHUD(), setServingTeam(), and startNewGame().
bool BV3D::Referee::mActive [protected]
Definition at line 75 of file Referee.h.
Referenced by BV3D::TieBreakReferee::ballOnBlobb(), BV3D::ClassicReferee::ballOnBlobb(), BV3D::TieBreakReferee::ballOnField(), BV3D::ClassicReferee::ballOnField(), getActive(), Referee(), and setActive().
The documentation for this class was generated from the following files:
Referee.h
Referee.cpp