BV3D documentation
BV3D::Ball
BV3D::Ball Class Reference
#include <Ball.h>
Public Member Functions
Ball (VRS::SO< BV3D::Arena > arena)
Ball.cpp.
~Ball ()
VRS::SO
< VRS::SceneThing > getScene ()
void resetPosition (VRS::Vector &position)
VRS::Vector getPosition ()
NewtonBody * getBody ()
Static Public Member Functions
static void applyForceAndTorqueCallback (const NewtonBody *body)
Protected Member Functions
void update ()
Detailed Description
Definition at line 21 of file Ball.h.
Constructor & Destructor Documentation
BV3D::Ball::Ball (VRS::SO< BV3D::Arena > arena)
Ball.cpp.
ctor
Parameters:
arena specifies the arena in which the ball is simulated
Definition at line 21 of file Ball.cpp.
References applyForceAndTorqueCallback(), BV3D::ballRadius, resetPosition(), BV3D::shadowHeight, and BV3D::threeDSPath.
BV3D::Ball::~Ball ()
dtor
Definition at line 64 of file Ball.cpp.
Member Function Documentation
VRS::SO<VRS::SceneThing> BV3D::Ball::getScene () [inline]
returns the local ball scene
Definition at line 38 of file Ball.h.
void BV3D::Ball::resetPosition (VRS::Vector & position)
position ball
Parameters:
position is the ball's new location
Definition at line 69 of file Ball.cpp.
References BV3D::shadowHeight, and BV3D::shadowMaxHeight.
Referenced by Ball().
VRS::Vector BV3D::Ball::getPosition ()
Definition at line 90 of file Ball.cpp.
NewtonBody* BV3D::Ball::getBody () [inline]
Definition at line 48 of file Ball.h.
void BV3D::Ball::update () [protected]
update ball physics and visuals
Definition at line 102 of file Ball.cpp.
References BV3D::gravity, BV3D::maxBallVelocity, BV3D::shadowHeight, and BV3D::shadowMaxHeight.
Referenced by applyForceAndTorqueCallback().
void BV3D::Ball::applyForceAndTorqueCallback (const NewtonBody * body) [static]
callback which notifies that a NewtonBody in the NewtonWorld has changed
Parameters:
body is the changed NewtonBody
Definition at line 94 of file Ball.cpp.
References update().
Referenced by Ball().
The documentation for this class was generated from the following files:
Ball.h
Ball.cpp