BV3D documentation
BV3D::Game
BV3D::Game Class Reference
The Game class represents an instance of the BlobbyVolley3D game.
#include <Game.h>
Public Member Functions
Game ()
~Game ()
void update ()
void processInput ()
VRS::SO< BV3D::Ball > getBall ()
VRS::SO< BV3D::Referee > getReferee ()
VRS::SO< BV3D::Blobb > getBlobb (BV3D::TEAM team)
VRS::SO< BV3D::Arena > getArena ()
void scheduleNewServe ()
void newServe ()
void playSoundTouch ()
void playSoundWhistle ()
void switchToGame (bool bRestart)
void toggleFullscreen ()
int getFrameCount ()
Protected Member Functions
void switchToMenu (bool allowResume)
void setupSound ()
void applyMenuSettings ()
void switchCameraposition (BV3D::CAMERAPOSITION position)
VRS::Vector getPositionVector (BV3D::CAMERAPOSITION position)
VRS::Vector getDirectionVector (BV3D::CAMERAPOSITION position)
bool isCameraMovieStyle ()
bool isCameraDistant ()
bool isCameraHigher ()
void setMovieStyleCamera (bool useMovieStyle)
void setCameraDistant (bool distant)
void setCameraHigher (bool higher)
bool isPaused ()
void setPaused (bool pauseGame)
Detailed Description
The Game class represents an instance of the BlobbyVolley3D game.
It is responsible for:
creating and managing:
the obvious game objects: the Arena, the Blobbs, the Ball and the Net
the canvas(window) to which the scene is rendered
the root scene node
the scene camera
hooking in/out the sub-scenes of the game objects
processing and dispatching of input events from the canvas
periodically issue rendering
Definition at line 58 of file Game.h.
Constructor & Destructor Documentation
BV3D::Game::Game ()
Definition at line 36 of file Game.cpp.
References BV3D::ARENA_EXTENT, BV3D::CLASSIC_CAMERA, BV3D::LOOK_FROM, BV3D::LOOK_TO, processInput(), setupSound(), switchToMenu(), BV3D::TEAM1, BV3D::TEAM2, and update().
BV3D::Game::~Game ()
Definition at line 128 of file Game.cpp.
Member Function Documentation
void BV3D::Game::update ()
called periodically on timer events to update the physics world and redisplay the whole scene - main callback
Definition at line 204 of file Game.cpp.
References isCameraMovieStyle(), isPaused(), BV3D::MAX_FPS, newServe(), BV3D::TEAM1, and BV3D::TEAM2.
Referenced by Game().
void BV3D::Game::processInput ()
evaluates incoming InputEvents from canvas, processes and dispatches them
Definition at line 249 of file Game.cpp.
References BV3D::CLASSIC_CAMERA, isCameraDistant(), isCameraHigher(), isCameraMovieStyle(), isPaused(), BV3D::REVERSE_CAMERA, setCameraDistant(), setCameraHigher(), setMovieStyleCamera(), setPaused(), switchCameraposition(), switchToMenu(), BV3D::TEAM1_BASECAMERA, and BV3D::TEAM2_BASECAMERA.
Referenced by Game().
VRS::SO<BV3D::Ball> BV3D::Game::getBall () [inline]
Definition at line 64 of file Game.h.
VRS::SO<BV3D::Referee> BV3D::Game::getReferee () [inline]
Definition at line 65 of file Game.h.
VRS::SO<BV3D::Blobb> BV3D::Game::getBlobb (BV3D::TEAM team) [inline]
Definition at line 66 of file Game.h.
References BV3D::TEAM1.
Referenced by switchToGame().
VRS::SO<BV3D::Arena> BV3D::Game::getArena () [inline]
Definition at line 67 of file Game.h.
void BV3D::Game::scheduleNewServe ()
causes a new serve in about 3 seconds (called by Referee)
Definition at line 326 of file Game.cpp.
void BV3D::Game::newServe ()
Definition at line 330 of file Game.cpp.
Referenced by switchToGame(), and update().
void BV3D::Game::playSoundTouch ()
Definition at line 407 of file Game.cpp.
void BV3D::Game::playSoundWhistle ()
Definition at line 411 of file Game.cpp.
void BV3D::Game::switchToGame (bool restart)
called by menu
Definition at line 349 of file Game.cpp.
References applyMenuSettings(), BV3D::ARENA_EXTENT, getBlobb(), newServe(), BV3D::TEAM1, and BV3D::TEAM2.
void BV3D::Game::toggleFullscreen ()
Definition at line 381 of file Game.cpp.
int BV3D::Game::getFrameCount () [inline]
Definition at line 74 of file Game.h.
void BV3D::Game::switchToMenu (bool allowResume) [protected]
Definition at line 369 of file Game.cpp.
Referenced by Game(), and processInput().
void BV3D::Game::setupSound () [protected]
Definition at line 396 of file Game.cpp.
References BV3D::SOUNDS_PATH.
Referenced by Game().
void BV3D::Game::applyMenuSettings () [protected]
Definition at line 132 of file Game.cpp.
References BV3D::Menu::AI, BV3D::Menu::BEACH, BV3D::CITY, BV3D::Menu::CLASSIC, BV3D::Menu::HEAVEN, BV3D::Menu::KB_ARROWS, BV3D::Menu::KB_WASDQ, BV3D::Menu::MOUSE, BV3D::TEAM1, and BV3D::TEAM2.
Referenced by switchToGame().
void BV3D::Game::switchCameraposition (BV3D::CAMERAPOSITION position) [protected]
Initializes a camera animation to the specified cameraposition. Animation style depends on weather setMovieStyleCamera is set to true. In movie-style mode every time the camera moves, the game is paused, and the camera always takes the long way to a new camera position
Definition at line 421 of file Game.cpp.
References BV3D::CLASSIC_CAMERA, getDirectionVector(), getPositionVector(), isCameraMovieStyle(), BV3D::MAX_CAMERAS, BV3D::REVERSE_CAMERA, BV3D::TEAM1_BASECAMERA, and BV3D::TEAM2_BASECAMERA.
Referenced by processInput().
VRS::Vector BV3D::Game::getPositionVector (BV3D::CAMERAPOSITION position) [protected]
Returns the position vector of the given camera position, modified in case setCameraDistant and/or setCameraHigher were set to true.
Definition at line 454 of file Game.cpp.
References BV3D::CLASSIC_CAMERA, isCameraDistant(), isCameraHigher(), BV3D::LOOK_FROM, BV3D::REVERSE_CAMERA, BV3D::TEAM1_BASECAMERA, and BV3D::TEAM2_BASECAMERA.
Referenced by switchCameraposition().
VRS::Vector BV3D::Game::getDirectionVector (BV3D::CAMERAPOSITION position) [protected]
Returns the direction vector of the given camera position, modified in case setCameraHigher was set to true.
Definition at line 479 of file Game.cpp.
References BV3D::CLASSIC_CAMERA, isCameraHigher(), BV3D::LOOK_FROM, BV3D::LOOK_TO, BV3D::REVERSE_CAMERA, BV3D::TEAM1_BASECAMERA, and BV3D::TEAM2_BASECAMERA.
Referenced by switchCameraposition().
bool BV3D::Game::isCameraMovieStyle () [inline, protected]
Definition at line 83 of file Game.h.
Referenced by processInput(), switchCameraposition(), and update().
bool BV3D::Game::isCameraDistant () [inline, protected]
Definition at line 84 of file Game.h.
Referenced by getPositionVector(), and processInput().
bool BV3D::Game::isCameraHigher () [inline, protected]
Definition at line 85 of file Game.h.
Referenced by getDirectionVector(), getPositionVector(), and processInput().
void BV3D::Game::setMovieStyleCamera (bool useMovieStyle) [inline, protected]
Definition at line 86 of file Game.h.
Referenced by processInput().
void BV3D::Game::setCameraDistant (bool distant) [inline, protected]
Definition at line 87 of file Game.h.
Referenced by processInput().
void BV3D::Game::setCameraHigher (bool higher) [inline, protected]
Definition at line 88 of file Game.h.
Referenced by processInput().
bool BV3D::Game::isPaused () [inline, protected]
Definition at line 89 of file Game.h.
Referenced by processInput(), and update().
void BV3D::Game::setPaused (bool pauseGame) [inline, protected]
Definition at line 90 of file Game.h.
Referenced by processInput().
The documentation for this class was generated from the following files:
Game.h
Game.cpp