BV3D documentation
BV3D::TieBreakReferee
BV3D::TieBreakReferee Class Reference
Implements the newer, tournament volleyball rules.
#include <TieBreakReferee.h>
Public Member Functions
TieBreakReferee (VRS::SO< BV3D::Game > game)
~TieBreakReferee (void)
void ballOnBlobb (BV3D::TEAM team)
void ballOnField (BV3D::TEAM team)
Detailed Description
Implements the newer, tournament volleyball rules.
The game goes until one team reaches a score of 25 or more with 2 or more points difference to the other team. Teams can touch the ball only 3 times before causing a fault each fault causes the other team to score a point and get to serve the ball.
Definition at line 15 of file TieBreakReferee.h.
Constructor & Destructor Documentation
BV3D::TieBreakReferee::TieBreakReferee (VRS::SO< BV3D::Game > game)
Sets up a Referee for new tournament volleyball rules, with a winning score of 25, a minimum difference between teams of 2 and a maximum of 3 contacts with the ball.
Definition at line 7 of file TieBreakReferee.cpp.
References BV3D::Referee::setMaximumContacts(), BV3D::Referee::setMinimumDifference(), and BV3D::Referee::setWinningScore().
BV3D::TieBreakReferee::~TieBreakReferee (void) [inline]
Definition at line 19 of file TieBreakReferee.h.
Member Function Documentation
void BV3D::TieBreakReferee::ballOnBlobb (BV3D::TEAM team) [virtual]
Handles the case when the ball collides with a blobb from a team. Increases the teams contact-counter and checks whether a fault occured. If that is the case it increases the opponents score and checks whether the game is now over. If not a new rally is started with the opponent team serving.
Implements BV3D::Referee.
Definition at line 20 of file TieBreakReferee.cpp.
References BV3D::Referee::gameOver(), BV3D::Referee::getMaximumContacts(), BV3D::Referee::getOpponent(), BV3D::Referee::increaseContacts(), BV3D::Referee::increaseScore(), BV3D::Referee::isGameOver(), BV3D::Referee::mActive, BV3D::Referee::mGame, BV3D::Referee::newServe(), and BV3D::Referee::resetContacts().
void BV3D::TieBreakReferee::ballOnField (BV3D::TEAM team) [virtual]
Handles the case when the ball touches the ground on a teams side. The opponent teams score is increased and a check is done whether the game is now over. The opponent team serves the new ball if the game is not over yet and all contact-counters are reset.
Implements BV3D::Referee.
Definition at line 53 of file TieBreakReferee.cpp.
References BV3D::Referee::gameOver(), BV3D::Referee::getOpponent(), BV3D::Referee::increaseScore(), BV3D::Referee::isGameOver(), BV3D::Referee::mActive, BV3D::Referee::mGame, BV3D::Referee::newServe(), and BV3D::Referee::resetContacts().
The documentation for this class was generated from the following files:
TieBreakReferee.h
TieBreakReferee.cpp