BV3D documentation
BV3D::SceneLoader
BV3D::SceneLoader Class Reference
SceneLoader is responsible for loading the surroundings of different scenes.
#include <SceneLoader.h>
Public Member Functions
SceneLoader (VRS::SO< VRS::Canvas > canvas)
~SceneLoader (void)
VRS::SO
< VRS::SceneThing > loadBeach ()
VRS::SO
< VRS::SceneThing > loadArena ()
VRS::SO
< VRS::SceneThing > loadHeaven ()
VRS::SO
< VRS::SceneThing > loadCity ()
Protected Member Functions
VRS::SO
< VRS::SceneThing > getDesertSkybox ()
VRS::SO
< VRS::SceneThing > getWaterscapeSkybox ()
VRS::SO
< VRS::SceneThing > getIslandsSkybox ()
VRS::SO
< VRS::SceneThing > getHotDesertSkybox ()
VRS::SO
< VRS::SceneThing > getBrightDaySkybox ()
VRS::SO
< VRS::SceneThing > getZolsky6Skybox ()
VRS::SO
< VRS::SceneThing > getZolsky8Skybox ()
VRS::SO
< VRS::SceneThing > getZolsky9Skybox ()
VRS::SO
< VRS::SceneThing > getCityNightSkybox ()
VRS::SO
< VRS::SceneThing > getFieldLines ()
Protected Attributes
VRS::SO< VRS::Canvas > mCanvas
VRS::SO< ModelOptimizer > mOptimizer
Detailed Description
SceneLoader is responsible for loading the surroundings of different scenes.
This includes the ground, objects in the vicinity of the field and some background. Several methods are given for loading different predefined skyboxes and whole sceneries.
NOTE: There are more skyboxes than we currently use, but we left them inside, since we plan to develop the game further.
Definition at line 30 of file SceneLoader.h.
Constructor & Destructor Documentation
BV3D::SceneLoader::SceneLoader (VRS::SO< VRS::Canvas > canvas)
Definition at line 24 of file SceneLoader.cpp.
References mCanvas, and mOptimizer.
BV3D::SceneLoader::~SceneLoader (void) [inline]
Definition at line 34 of file SceneLoader.h.
Member Function Documentation
VRS::SO< VRS::SceneThing > BV3D::SceneLoader::loadBeach ()
Returns a scene graph, which includes a complete scenerie of a beach.
Definition at line 55 of file SceneLoader.cpp.
References BV3D::ModelOptimizer::ALL_AND_NO_OPTIMIZATIONS, BV3D::ARENA_EXTENT, bumpmapOffset, getFieldLines(), getZolsky8Skybox(), BV3D::GRAFICS_PATH, mCanvas, BV3D::MODELS_PATH, and mOptimizer.
VRS::SO< VRS::SceneThing > BV3D::SceneLoader::loadArena ()
Returns a scene graph, including the scenerie of a kind of playground with a fenced-in field.
Definition at line 175 of file SceneLoader.cpp.
References BV3D::ARENA_EXTENT, bumpmapOffset, getFieldLines(), getZolsky9Skybox(), BV3D::GRAFICS_PATH, mCanvas, BV3D::MODELS_PATH, mOptimizer, and BV3D::ModelOptimizer::NO_MATERIAL_NO_TEXTURES.
VRS::SO< VRS::SceneThing > BV3D::SceneLoader::loadHeaven ()
Returns a minimalistic scenerie of a closed carpet of clouds for the blobbs to play on.
Definition at line 289 of file SceneLoader.cpp.
References BV3D::ARENA_EXTENT, getFieldLines(), and BV3D::GRAFICS_PATH.
VRS::SO< VRS::SceneThing > BV3D::SceneLoader::loadCity ()
Returns a scene graph of a city by night with the blobbs playing on a miniature field on top of a concrete pillar.
Definition at line 317 of file SceneLoader.cpp.
References BV3D::ARENA_EXTENT, getCityNightSkybox(), getFieldLines(), BV3D::GRAFICS_PATH, mCanvas, BV3D::MODELS_PATH, and mOptimizer.
VRS::SO<VRS::SceneThing> BV3D::SceneLoader::getDesertSkybox () [protected]
VRS::SO< VRS::SceneThing > BV3D::SceneLoader::getWaterscapeSkybox () [protected]
Low-Res(256x256) Skybox of Water with a few hills.
Definition at line 357 of file SceneLoader.cpp.
References BV3D::GRAFICS_PATH.
VRS::SO< VRS::SceneThing > BV3D::SceneLoader::getIslandsSkybox () [protected]
768x768 skybox of nice water, rising sund and hills
Definition at line 376 of file SceneLoader.cpp.
References BV3D::GRAFICS_PATH.
VRS::SO< VRS::SceneThing > BV3D::SceneLoader::getHotDesertSkybox () [protected]
Low-Res(256x256) skybox of desert with sun
Definition at line 395 of file SceneLoader.cpp.
References BV3D::GRAFICS_PATH.
VRS::SO< VRS::SceneThing > BV3D::SceneLoader::getBrightDaySkybox () [protected]
512x512 skybox of prairie with blue sky and clouds
Definition at line 414 of file SceneLoader.cpp.
References BV3D::GRAFICS_PATH.
VRS::SO< VRS::SceneThing > BV3D::SceneLoader::getZolsky6Skybox () [protected]
512x512 skybox of white desert
Definition at line 433 of file SceneLoader.cpp.
References BV3D::GRAFICS_PATH.
VRS::SO< VRS::SceneThing > BV3D::SceneLoader::getZolsky8Skybox () [protected]
512x512 skybox of setting sun on water
Definition at line 452 of file SceneLoader.cpp.
References BV3D::GRAFICS_PATH.
Referenced by loadBeach().
VRS::SO< VRS::SceneThing > BV3D::SceneLoader::getZolsky9Skybox () [protected]
512x512 skybox of city
Definition at line 471 of file SceneLoader.cpp.
References BV3D::GRAFICS_PATH.
Referenced by loadArena().
VRS::SO< VRS::SceneThing > BV3D::SceneLoader::getCityNightSkybox () [protected]
512x512 skybox of a city square by night
Definition at line 490 of file SceneLoader.cpp.
References BV3D::GRAFICS_PATH.
Referenced by loadCity().
VRS::SO< VRS::SceneThing > BV3D::SceneLoader::getFieldLines () [protected]
Returns a scene graph, which includes white lines(base- and sidelines) that fit the extent of the gamefield.
Definition at line 33 of file SceneLoader.cpp.
References BV3D::ARENA_EXTENT, and BV3D::LINES_WIDTH.
Referenced by loadArena(), loadBeach(), loadCity(), and loadHeaven().
Member Data Documentation
VRS::SO<VRS::Canvas> BV3D::SceneLoader::mCanvas [protected]
Definition at line 42 of file SceneLoader.h.
Referenced by loadArena(), loadBeach(), loadCity(), and SceneLoader().
VRS::SO<ModelOptimizer> BV3D::SceneLoader::mOptimizer [protected]
Definition at line 43 of file SceneLoader.h.
Referenced by loadArena(), loadBeach(), loadCity(), and SceneLoader().
The documentation for this class was generated from the following files:
SceneLoader.h
SceneLoader.cpp