BV3D documentation
BV3D::ModelOptimizer
BV3D::ModelOptimizer Class Reference
Class for loading and optimizing external 3D-models, currently supporting .obj and .3ds files.
#include <ModelOptimizer.h>
Public Types
enum ReadMode { MATERIAL_AND_TEXTURES, ONLY_MATERIAL, NO_MATERIAL_NO_TEXTURES, ALL_AND_NO_OPTIMIZATIONS }
Public Member Functions
ModelOptimizer (void)
virtual ~ModelOptimizer (void)
VRS::SO
< VRS::SceneThing > get3dsModel (const std::string &fileName, bool useStaticLighting=true, ReadMode readMode=ONLY_MATERIAL)
VRS::SO
< VRS::SceneThing > getWavefrontModel (const std::string &fileName)
Protected Member Functions
VRS::SO
< VRS::SceneThing > optimizeModel (VRS::SO< VRS::SceneThing > model)
Protected Attributes
bool mStaticLighting
Detailed Description
Class for loading and optimizing external 3D-models, currently supporting .obj and .3ds files.
Definition at line 18 of file ModelOptimizer.h.
Member Enumeration Documentation
enum BV3D::ModelOptimizer::ReadMode
Enumerator:
MATERIAL_AND_TEXTURES
ONLY_MATERIAL
NO_MATERIAL_NO_TEXTURES
ALL_AND_NO_OPTIMIZATIONS
Definition at line 24 of file ModelOptimizer.h.
Constructor & Destructor Documentation
BV3D::ModelOptimizer::ModelOptimizer (void) [inline]
Definition at line 21 of file ModelOptimizer.h.
References mStaticLighting.
virtual BV3D::ModelOptimizer::~ModelOptimizer (void) [inline, virtual]
Definition at line 22 of file ModelOptimizer.h.
Member Function Documentation
VRS::SO< VRS::SceneThing > BV3D::ModelOptimizer::get3dsModel (const std::string & fileName, bool useStaticLighting = true, ReadMode readMode = ONLY_MATERIAL)
Loads a 3ds model with the given options and optimizes it
Definition at line 13 of file ModelOptimizer.cpp.
References ALL_AND_NO_OPTIMIZATIONS, MATERIAL_AND_TEXTURES, mStaticLighting, NO_MATERIAL_NO_TEXTURES, ONLY_MATERIAL, and optimizeModel().
VRS::SO< VRS::SceneThing > BV3D::ModelOptimizer::getWavefrontModel (const std::string & fileName)
Loads an obj model and optimizes it
Definition at line 46 of file ModelOptimizer.cpp.
References optimizeModel().
VRS::SO< VRS::SceneThing > BV3D::ModelOptimizer::optimizeModel (VRS::SO< VRS::SceneThing > origModel) [protected]
Optimizes the given Scenegraph and returns a new one.
Definition at line 58 of file ModelOptimizer.cpp.
References mStaticLighting.
Referenced by get3dsModel(), and getWavefrontModel().
Member Data Documentation
bool BV3D::ModelOptimizer::mStaticLighting [protected]
Definition at line 35 of file ModelOptimizer.h.
Referenced by get3dsModel(), ModelOptimizer(), and optimizeModel().
The documentation for this class was generated from the following files:
ModelOptimizer.h
ModelOptimizer.cpp